h

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -22,6 +22,17 @@ jobs:
       - name: Build backend image
         run: docker build -t linkedin-backend ./backend
 
+      - name: Check if DOCKER_USERNAME is set
+      
+        run: |
+          if [[ -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
+          echo "ERROR: DOCKER_USERNAME is not set!"
+          exit 1
+          else
+          echo "DOCKER_USERNAME is set."
+          fi
+
+
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
